project_id = "rtaomiqsnctigleqjojt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.check-master-admin-exists]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.ai-generate-product-types]
verify_jwt = true

[functions.ai-optimize-product]
verify_jwt = false

[functions.analyze-brand-tone]
verify_jwt = true

[functions.analyze-edit-patterns]
verify_jwt = true

[functions.fetch-shopify-analytics]
verify_jwt = true

[functions.find-best-price]
verify_jwt = true

[functions.generate-ai-insights]
verify_jwt = true

[functions.manage-products]
verify_jwt = true

[functions.shopify-products]
verify_jwt = false

[functions.sync-orders]
verify_jwt = true

[functions.sync-shopify-products]
verify_jwt = true

[functions.sync-ebay-products]
verify_jwt = true

[functions.update-performance-metrics]
verify_jwt = true

[functions.update-store-config]
verify_jwt = true

[functions.ebay-webhook-handler]
verify_jwt = false

[functions.ebay-oauth-callback]
verify_jwt = false

[functions.ebay-oauth-url]
verify_jwt = false

[functions.ups-oauth-url]
verify_jwt = true

[functions.ups-oauth-callback]
verify_jwt = false

[functions.ups-rating]
verify_jwt = true

[functions.ups-shipment]
verify_jwt = true

[functions.test-ups-auth]
verify_jwt = true

[functions.refresh-ups-token]
verify_jwt = true

[functions.clear-ups-token]
verify_jwt = true

[functions.test-ups-oauth-flow]
verify_jwt = true

[functions.validate-ups-credentials]
verify_jwt = true

[functions.canada-post-oauth-url]
verify_jwt = true

[functions.canada-post-setup]
verify_jwt = true

[functions.create-master-admin]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = true

[functions.send-confirmation-email]
verify_jwt = false

[functions.shipstation-get-rates]
verify_jwt = true

[functions.shipstation-create-label]
verify_jwt = true

[functions.shipstation-track-shipment]
verify_jwt = true

[functions.shipstation-validate-credentials]
verify_jwt = true

[functions.shipstation-get-services]
verify_jwt = true

[functions.shipstation-webhook]
verify_jwt = false

[functions.canada-post-shipment]
verify_jwt = true

[functions.canada-post-label-download]
verify_jwt = true

[functions.canada-post-rating]
verify_jwt = true

[functions.canada-post-oauth-callback]
verify_jwt = false

[functions.calculate-shipping-rates]
verify_jwt = true

[functions.send-test-email]
verify_jwt = true

[functions.activate-carrier]
verify_jwt = true

[functions.carrier-rates]
verify_jwt = true

[functions.carrier-shipment]
verify_jwt = true

[functions.fetch-shipping-services]
verify_jwt = true

[functions.shipping-rate-summary]
verify_jwt = true

[functions.bulk-update-order-statuses]
verify_jwt = true

[functions.update-order-statuses]
verify_jwt = true

[functions.ai-shipping-optimizer]
verify_jwt = true

[functions.ai-shipping-rules-generator]
verify_jwt = true

[functions.test-ups-negotiated-rates]
verify_jwt = true

[functions.refresh-ups-token-manual]
verify_jwt = true

[functions.setup-ups-credentials]
verify_jwt = true

[functions.test-shopify-connection]
verify_jwt = true

[functions.test-ups-with-exact-address]
verify_jwt = true

[functions.debug-ups-rating]
verify_jwt = true

[functions.ups-diagnostic]
verify_jwt = true