// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtaomiqsnctigleqjojt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0YW9taXFzbmN0aWdsZXFqb2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDI5MjIsImV4cCI6MjA2NTQxODkyMn0.QOrBY1cIqS1YfdXdrm7pGB6U0E8nGYCsYQH_u5XVQPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});